//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExampleProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Doctor()
        {
            this.tbl_appointment = new HashSet<tbl_appointment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> years_of_exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_appointment> tbl_appointment { get; set; }
    }
}
