//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Da6_Question.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_appointment
    {
        public int app_id { get; set; }
        public Nullable<int> docid { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> app_date { get; set; }
        public Nullable<int> app_time { get; set; }
    
        public virtual tbl_Doctor tbl_Doctor { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
    }
}
