//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day8_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> years_of_exp { get; set; }
        public string phone { get; set; }
        public string username { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
